---
services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: P@ssw0rd12345!
      MSSQL_PID: Developer
    ports: [1433:1433]
    healthcheck:
      test:
        - CMD-SHELL
        - /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P $$MSSQL_SA_PASSWORD
          -C -Q 'SELECT 1' || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
  api:
    build: .
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: Server=db,1433;Database=MasarifDb;User Id=sa;Password=P@ssw0rd12345!;TrustServerCertificate=True;
    depends_on:
      db:
        condition: service_healthy
    ports: [8080:8080]
